name: eks-pulumi-gitops
description: ArgoCD + GitOps-Bridge bootstrap for the eks-pulumi project (slice 3 of 3)
runtime:
    name: nodejs
    options:
        packagemanager: pnpm
config:
    pulumi:tags:
        value:
            pulumi:template: aws-typescript
