name: eks-pulumi-cluster
description: EKS cluster + IAM + node groups for the eks-pulumi project (slice 2 of 3)
runtime:
    name: nodejs
    options:
        packagemanager: pnpm
config:
    pulumi:tags:
        value:
            pulumi:template: aws-typescript
