// AWS Client VPN with mTLS auth — full PKI generated by @pulumi/tls,
// server cert in ACM, single shared client cert embedded in the .ovpn.
//
// Same-CA pattern: ONE ACM certificate (the server cert) is reused as both
// `serverCertificateArn` and `rootCertificateChainArn`. AWS accepts this when
// client and server certs are issued by the same CA — the CA cert chained on
// the server's ACM upload is what AWS uses to validate inbound client certs.
// https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/mutual.html
//
// .ovpn structure (inline <ca>/<cert>/<key>) per:
// https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-getting-started.html
//
// `clientOvpn` is wrapped in pulumi.secret so it's only visible under
// `pulumi stack output --show-secrets` (consumed by `make vpn-config`).

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as tls from "@pulumi/tls";

import { prefix, clientVpnCidr, vpnHighAvailability, azCount } from "../pulumi.config";
import { vpcId, vpcCidrBlock, privateSubnetIds } from "./vpc";

// CA -------------------------------------------------------------------------

const caKey = new tls.PrivateKey(`${prefix}-vpn-ca-key`, {
    algorithm: "RSA",
    rsaBits: 4096,
});

const caCert = new tls.SelfSignedCert(`${prefix}-vpn-ca-cert`, {
    privateKeyPem: caKey.privateKeyPem,
    subject: { commonName: `${prefix}-vpn-ca` },
    isCaCertificate: true,
    validityPeriodHours: 87600, // 10 years
    allowedUses: ["cert_signing", "crl_signing", "digital_signature"],
});

// Server cert (uploaded to ACM) ---------------------------------------------

const serverKey = new tls.PrivateKey(`${prefix}-vpn-server-key`, {
    algorithm: "RSA",
    rsaBits: 2048,
});

const serverCsr = new tls.CertRequest(`${prefix}-vpn-server-csr`, {
    privateKeyPem: serverKey.privateKeyPem,
    subject: { commonName: "server" },
});

const serverCert = new tls.LocallySignedCert(`${prefix}-vpn-server-cert`, {
    certRequestPem: serverCsr.certRequestPem,
    caPrivateKeyPem: caKey.privateKeyPem,
    caCertPem: caCert.certPem,
    validityPeriodHours: 8760, // 1 year
    allowedUses: ["server_auth", "digital_signature", "key_encipherment"],
});

// Client cert (single shared, NOT uploaded to ACM) --------------------------

const clientKey = new tls.PrivateKey(`${prefix}-vpn-client-key`, {
    algorithm: "RSA",
    rsaBits: 2048,
});

const clientCsr = new tls.CertRequest(`${prefix}-vpn-client-csr`, {
    privateKeyPem: clientKey.privateKeyPem,
    subject: { commonName: "client-shared" },
});

const clientCert = new tls.LocallySignedCert(`${prefix}-vpn-client-cert`, {
    certRequestPem: clientCsr.certRequestPem,
    caPrivateKeyPem: caKey.privateKeyPem,
    caCertPem: caCert.certPem,
    validityPeriodHours: 8760, // 1 year
    allowedUses: ["client_auth", "digital_signature", "key_encipherment"],
});

// ACM — single cert, reused as server + root chain --------------------------

const serverAcm = new aws.acm.Certificate(`${prefix}-vpn-server-acm`, {
    privateKey: serverKey.privateKeyPem,
    certificateBody: serverCert.certPem,
    certificateChain: caCert.certPem,
    tags: { Name: `${prefix}-vpn-server` },
});

// Connection logs ------------------------------------------------------------

const connLogGroup = new aws.cloudwatch.LogGroup(`${prefix}-vpn-logs`, {
    name: `/aws/clientvpn/${prefix}`,
    retentionInDays: 30,
});

// Security group -------------------------------------------------------------
//
// Client VPN endpoint requires an SG that permits inbound UDP 443 from the
// internet (clients connect to the AWS-managed endpoint NLB).

const vpnSg = new aws.ec2.SecurityGroup(`${prefix}-vpn-sg`, {
    name: `${prefix}-vpn-sg`,
    vpcId: vpcId,
    description: "Client VPN endpoint SG",
    tags: { Name: `${prefix}-vpn-sg` },
});

new aws.vpc.SecurityGroupIngressRule(`${prefix}-vpn-sg-udp443`, {
    securityGroupId: vpnSg.id,
    ipProtocol: "udp",
    fromPort: 443,
    toPort: 443,
    cidrIpv4: "0.0.0.0/0",
    description: "OpenVPN UDP 443 from anywhere",
});

new aws.vpc.SecurityGroupEgressRule(`${prefix}-vpn-sg-egress`, {
    securityGroupId: vpnSg.id,
    ipProtocol: "-1",
    cidrIpv4: "0.0.0.0/0",
    description: "All egress",
});

// Endpoint -------------------------------------------------------------------

const endpoint = new aws.ec2clientvpn.Endpoint(`${prefix}-vpn`, {
    description: `${prefix} client VPN`,
    clientCidrBlock: clientVpnCidr,
    serverCertificateArn: serverAcm.arn,
    authenticationOptions: [{
        type: "certificate-authentication",
        rootCertificateChainArn: serverAcm.arn, // same-CA pattern
    }],
    connectionLogOptions: {
        enabled: true,
        cloudwatchLogGroup: connLogGroup.name,
    },
    splitTunnel: true,
    vpcId: vpcId,
    securityGroupIds: [vpnSg.id],
    transportProtocol: "udp",
    vpnPort: 443,
});

// Subnet association(s). Default (vpnHighAvailability=false): one association
// on privateSubnetIds[0] — minimum cost (~$72/mo). HA mode: one association
// per private subnet (one per AZ) so a single-AZ outage no longer kills VPN
// access — adds ~$72/mo per extra association. AWS load-balances connections
// across the available associations via the endpoint DNS name.
// https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-target.html
if (vpnHighAvailability) {
    // Loop bound tracks vpc.ts's azCount so HA assoc count matches the
    // private subnet count exactly (no out-of-range index, no uncovered AZ).
    for (let i = 0; i < azCount; i++) {
        new aws.ec2clientvpn.NetworkAssociation(`${prefix}-vpn-assoc-${i}`, {
            clientVpnEndpointId: endpoint.id,
            subnetId: privateSubnetIds.apply(ids => ids[i]),
        });
    }
} else {
    new aws.ec2clientvpn.NetworkAssociation(`${prefix}-vpn-assoc`, {
        clientVpnEndpointId: endpoint.id,
        subnetId: privateSubnetIds.apply(ids => ids[0]),
    });
}

new aws.ec2clientvpn.AuthorizationRule(`${prefix}-vpn-auth`, {
    clientVpnEndpointId: endpoint.id,
    targetNetworkCidr: vpcCidrBlock,
    authorizeAllGroups: true,
    description: "Allow VPN clients to reach the entire VPC CIDR",
});

// .ovpn assembly -------------------------------------------------------------

const ovpn = pulumi
    .all([endpoint.dnsName, caCert.certPem, clientCert.certPem, clientKey.privateKeyPem])
    .apply(([dns, caPem, certPem, keyPem]) => `client
dev tun
proto udp
remote ${dns} 443
remote-random-hostname
resolv-retry infinite
nobind
remote-cert-tls server
cipher AES-256-GCM
verb 3
<ca>
${caPem.trim()}
</ca>
<cert>
${certPem.trim()}
</cert>
<key>
${keyPem.trim()}
</key>
reneg-sec 0
`);

// Exports --------------------------------------------------------------------

export const clientVpnEndpointId: pulumi.Output<string> = endpoint.id;
export const clientOvpn: pulumi.Output<string> = pulumi.secret(ovpn);
